# Generated by Django 5.2.4 on 2025-07-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.CharField(default=None, verbose_name='картинка'),
        ),
    ]
